name: The Hoplite Carver
favicon: null
layout_spectrum: 0.9868596738670021
typography_spectrum: 0.6726562650874257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6670505551155657
  lightness: 0.9722624935675412
  saturation: 0.2842137103434652
  rhythmicContrast: 0.6441752333194017
purpose: []
